In [1]:
import torch

In [2]:
x=torch.tensor([4.,2])
x

tensor([4., 2.])

In [3]:
d=torch.tensor([[2.,4],[4.,8]])
d

tensor([[2., 4.],
        [4., 8.]])

In [4]:
z=print (x*d)
z

tensor([[ 8.,  8.],
        [16., 16.]])


In [5]:
d.dtype

torch.float32

In [6]:
x.shape

torch.Size([2])

In [7]:
print (d)
d.shape

tensor([[2., 4.],
        [4., 8.]])


torch.Size([2, 2])

In [8]:
a=torch.tensor([[[2,4],[3,5]],[[3,5],[4.,6]],[[0,0],[3,3]]])
a

tensor([[[2., 4.],
         [3., 5.]],

        [[3., 5.],
         [4., 6.]],

        [[0., 0.],
         [3., 3.]]])

In [9]:
x = torch.tensor(9.) 

w = torch.tensor(20. , requires_grad = True)

b = torch.tensor(8. , requires_grad = True)

In [10]:
y = w * x + b
y

tensor(188., grad_fn=<AddBackward0>)

In [11]:
y.backward()

In [12]:
print('dy/dx:' , x.grad)
print('dy/dw:' , w.grad)
print('dy/db:' , b.grad)

dy/dx: None
dy/dw: tensor(9.)
dy/db: tensor(1.)
